inherit_from: ../base.yaml

render:
  target_video_name: demo_main_localization
  target_run_dir: outputs/runs/noise_sweep

experiment:
  name: demo_main_localization
  notes: render main localization demo video

